---
title: Subscription lifecycle
---
stateDiagram-v2
  direction LR
  [creation] --> incomplete: drafted
  [creation] --> trialing: has_trial
  [creation] --> recurring: created
  trialing --> recurring: trial_over
  incomplete --> recurring: start
  state recurring {
    active --> active: recure
    active --> paused: pause
    paused --> active: resume
  }
  incomplete --> cancelled: cancel
  recurring --> cancelled: cancel
